
version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    command: >
      sh -c "python manage.py migrate --settings=config.settings && python manage.py runserver 0.0.0.0:8000 --settings=config.settings"
    environment:
      - DB_HOST=db
      - DB_NAME=db
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db
      - redis
  celery:
    build:
      context: ..
      dockerfile: ./docker/celery/Dockerfile
  db:
    image: ankane/pgvector
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    container_name: "redis-container"
    ports:
      - "6379:6379"

volumes:
  db:
    driver: local
